apiVersion: v1
kind: Secret
metadata:
  name: notifications-api-secret
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=postgres;Port=5432;Database=fcg_notifications_db;Username=notifications;Password=notificationspw"
  RabbitMq__Password: guest
